### ISSUE TITLE
Update external file downloads through Butler

### ISSUE THREAD

**Issue by philomory** [itchio/butler#104]
In addition to my two regular downloads, I have a source download on my game page that points to current release version's tag on Bitbucket (e.g. https://bitbucket.org/philomory/ld38/get/0.2.0.zip). It would be nice to be able to use butler to update that external file link to point to the correct version when that changes.

**Comment by fasterthanlime** [comment]
What's the rationale behind having an external upload point to bitbucket? Providing a mirror?

**Comment by Chaser324** [comment]
I assume it's just the easiest way for them to distribute the source code. Does Bitbucket not have just a simple way to just link to the latest source archive (github.com/name/project/archive/master.zip) or latest release (github.com/user/project/releases/latest)?

That said, this doesn't seem like functionality that's in the scope of what Butler does.

**Comment by quyse** [comment]
> Does Bitbucket not have just a simple way to just link to the latest source archive (github.com/name/project/archive/master.zip) or latest release (github.com/user/project/releases/latest) so that it wouldn't be necessary to update the link?

Seems like it does: https://bitbucket.org/philomory/ld38/get/default.zip works.

**Comment by philomory** [comment]
So, default is no good, because that'll just get the absolute latest source, not necessarily the latest _release_ source; of course, I could easily create a 'release' tag and move it each time I push a release, and I'll probably end up doing so; however, I assume when I do that, an itch user looking at the page wouldn't be able to tell any difference before or after the target file was altered. I had assumed (perhaps erroneously!) that updating the link to point to a new URL would result in the same sort of behavior that pushing a new release does.

**Comment by Chaser324** [comment]
Well, one option would be to modify your branch structure to make the default always be your latest released code. Do all of your work on a dev branch and only merge to the master branch when you do a new release build.

**Comment by philomory** [comment]
Actually, I think I was labelling under several misconceptions that make this issue a moot point; Butler's  inclusion of the `userversion` flag led me to believe that the version number was actually visible to site visitors, but apparently that is not the case? As far as I can tell when looking at both the website and the app, anyways. In any case, I was hoping to achieve similar behavior for the source link (such that when I pushed a new release tag to Bitbucket, the a visitor to itch could _tell_ it was new), but if that's not actually behavior for normal downloads it doesn't really need to be there for the source download either.

My apologies for the confusion.

**Comment by fasterthanlime** [comment]
> Butler's inclusion of the userversion flag led me to believe that the version number was actually visible to site visitors, but apparently that is not the case?

Actually, it is: 

![image](https://cloud.githubusercontent.com/assets/7998310/26544620/af3c7096-4462-11e7-8715-486cbc72bb33.png)

But maybe not when purchases are disabled altogether - in which case, that's a bug we can fix.

 ---

@philomory Would uploading an archive of your code *via butler* be an option? With userversion and all?

I was asking "why" instead of responding to the "how", because external uploads are probably not going to be there forever. It's very useful for us to have uploads that:

  * Are served from a consistently fast CDN (personal web servers don't qualify)
  * Serve the file immediately, with a proper Content-Type, without showing an html page first (see google drive, dropbox, etc.)
  * Supports Range requests (for resumable downloads in app)
  * Are stored on our servers so we can scan them (for automatic tagging, malware detection, etc.)
  * Are durable (don't disappear when a file hoster goes out of business / a personal web server doesn't get renewed).
  * Have an immutable "url <=> content" relationship (the content doesn't change from under us, Useful for game updates from within the app, but also resumable downloads, even in a browser).

Originally, folks used external uploads mostly to overcome the 500MB limit. Since butler supports uploading up to 32GB, that's no longer an issue.

They also used it to automate their release process (have a single URL pointing to "latest"). Since butler can be automated, that's no longer an issue either. (There's a bunch of folks pointing out that GitHub/BitBucket have handy release processes - but there's nothing preventing anyone from bridging those together. We might even offer that at some point.

So, before we eventually disable external uploads, I'm on the look-out for use cases we're not covering yet!

**Comment by philomory** [comment]
@fasterthanlime Uploading the source via butler is probably a better way to handle it. However, that process would be a bit nicer if it there were a way to tell butler to exclude files from the upload folder (and not just ignore their differences), so I don't need to manually shuffle around `.hgignore`'ed files; that should be a separate feature request, I guess.

I do, wonder, though: when uploading a source bundle, is it an issue that there's no executable present? Is there a particular best-practice for platform-flagging such a download? Would I be better off just relying on the "External Links" metadata's "Source Code" link type? How does that metadata actually get used, if at all? If there's a best-practices document for that sort of thing, I'd love to see it.

Also, yes, it seems like version numbers are not visible when purchasing is disabled:
![itch2](https://cloud.githubusercontent.com/assets/200123/26568570/28c584a6-44a0-11e7-91f6-e38ff08b857b.png)
