### ISSUE TITLE
Progress spam in Gitlab CI log

### ISSUE THREAD

**Issue by quyse** [itchio/butler#126]
I would like to avoid spam from `butler push` in Gitlab CI log:
![2017-08-22-154850_653x722_scrot](https://user-images.githubusercontent.com/416215/29566165-7c72ec80-8751-11e7-81ee-59dd2d7088d2.png)

I guess butler doesn't detect a non-interactive console, and Gitlab CI cannot handle `\r` correctly. Maybe a `--quiet` or `--no-progress` flag could be added? Note that this is happening for me only for Windows builder; Linux and macOS don't print progress in CI log.

**Comment by fasterthanlime** [comment]
> I guess butler doesn't detect a non-interactive console

Actually, it does: https://github.com/itchio/butler/blob/678ef99eb840afded4c292cf52f729335a3fb91e/main.go#L581

Your windows runner is showing progress because.. there's no way (that I know of) to tell apart terminals from redirected outputs in windows, so it's just hardcoded to true: https://github.com/itchio/butler/blob/2c524f7e5403b35fe2c00984acb6f3be4bd41519/term_win.go

You could pass `--no-progress` yourself, though :)

**Comment by quyse** [comment]
> You could pass --no-progress yourself, though :)

Oh, thanks! `butler push --help` didn't show that. It'll work.

**Comment by fasterthanlime** [comment]
> Oh, thanks! butler push --help didn't show that. It'll work.

Right! There's a bunch of stuff hidden from butler help to keep it concise, need to find a better way to do that.

**Comment by quyse** [comment]
> You could pass --no-progress yourself, though :)

Correction: it's `--noprogress`, not `--no-progress` ;)

**Comment by fasterthanlime** [comment]
Good catch!

https://github.com/itchio/butler/blob/5e4fced596e93775d18823972ebb113b712b8fab/main.go#L118-L120

**Comment by temportalflux** [comment]
This option (and others) are missing from the documentation - can the doc pages at https://itch.io/docs/butler/pushing.html be updated?
