### ISSUE TITLE
'clean' command crashes on non-existent files

### ISSUE THREAD

**Issue by 200sc** [itchio/butler#140]
If a file passes the `os.IsNotExist` check after failing `os.Lstat` (https://github.com/itchio/butler/blob/master/cmd/clean/clean.go#L49-L52), the loop in `clean` continues to execute and hits a nil pointer with the `stat` variable (https://github.com/itchio/butler/blob/master/cmd/clean/clean.go#L58).

This commit: https://github.com/springboardVR/butler/commit/974aa9625fb58a2763bd4a7d56ba76bfe2f9392a fixes this, and includes tests to replicate the issue without that fix.

**Comment by fasterthanlime** [comment]
I rewrote your test in https://github.com/itchio/butler/commit/8be2a0da8c347a35fd5bd30c54badea6f5a9fb14

  * Use `wtest.Must` to fail early in case of internal errors
  * Use `errors.Wrap()` liberally to get useful stack traces
  * Use `ioutil.WriteFile` to write the plan in most cases (shorter)
  * Never use a relative temporary folder (inside the source tree) - instead, use `ioutil.TempDir`
  * Use `%#v` when generating the JSON, so that it quotes strings properly
  * Use 0755 for directories, 0644 for files as modes (`os.ModeDir` is something different - the tests failed on Linux & macOS because of that).
  * Don't bother checking errors when cleaning up directories (in defer) - if we can't clean them up, then there's nothing we can do about it, failing the tests won't help.
  * In TestHappyPath, make sure the files are actually gone aftewards :)
