### ISSUE TITLE
'sign' command fails to close created signature file if compression fails

### ISSUE THREAD

**Issue by 200sc** [itchio/butler#143]
If this code in `cmd/sign`: https://github.com/itchio/butler/blob/71361b9d8247268628c5123179f0b1208bd7c666/cmd/sign/sign.go#L67-L70 errors, an error is returned without closing the above `signatureWriter`. This also applies down the line should `pwr.ComputeSignatureToWriter` fail, although I am reasonably confident it can't.

**Comment by fasterthanlime** [comment]
I'm generally in favor of `Close()` hygiene, but let's review what would actually happen here:

  * The file at `*args.signature` would contain a wharf signature header
  * Not calling `Close()` might leave some data unflushed, if the program exits before the `*os.File` instance is garbage-collected

My thinking here is that if `pwr.CompressWire` or `pwr.ComputeSignatureToWriter` fail, the resulting file is unusable anyway, so does it really matter if we flush everything we had so far or not?

Or is your worry that opening a file for writing on some versions of Windows locks it and you wouldn't be able to open it right after?

The reason `sigWire.Close()` in this particular file is near the end is precisely because the signature files are compressed: `Close()` here doesn't just free resources, it flushes the compressor (which might be several megabytes of data, depending on the output format).

**Comment by fasterthanlime** [comment]
Perhaps a good fix would be to make `WriteContext.Close()` not close the underlying writer, and
just `defer signatureWriter.Close()` right after it's created instead.

This way the OS resource is always freed, and we only flush the compressor if we ran through the whole process successfully.

I've been feeling bad about this pattern anyway:

```go
// Close closes the underlying writer if it implements io.Closer
func (w *WriteContext) Close() error {
	if c, ok := w.writer.(io.Closer); ok {
		err := c.Close()
		if err != nil {
			return errors.Wrap(err, 1)
		}
	}

	return nil
}
```

**Comment by 200sc** [comment]
My primary worry is the Windows thing, yes, if the file never gets closed, nothing else attempting to interact with it would be able to. Not that there's necessarily anything meaningful in the file to interact with, I suppose.

**Comment by fasterthanlime** [comment]
I just checked: calling `*os.File.Close()` twice just returns `os.ErrClosed`, so it's fine to do it unconditionally in a defer without checking the return value.
