### ISSUE TITLE
Set a display name in butler push commands

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/butler#174]
One thing I'd like to be able to do on butler commands is change the display name of updated builds (the ones that display here):

![image](https://user-images.githubusercontent.com/2874150/51024483-9669ee80-1581-11e9-95d4-33e463b180d6.png)

It would be nice to be able to do something like this in my upload batch files:

`butler push ../builds/windows64/ terrycavanagh/dicey-dungeons:windows64 --userversion %VERSIONNUM% --displayname "Dicey Dungeons v%VERSIONNUM% Windows"`

(Again, apologies if this is already possible and I just missed it, am new to Butler and couldn't find it in the documentation!)

**Comment by fasterthanlime** [comment]
Are you planning on using this for anything other than showing the version number?

Because the version number is already shown for all butler-powered uploads (it's in your screenshot!). See #28

**Comment by TerryCavanagh** [comment]
I basically just think it looks nice to be able to choose an exact filename - for Dicey Dungeons, I'd use `Dicey Dungeons v%VERSIONNUM% Windows` and so on!

Basically, this bit:

![image](https://user-images.githubusercontent.com/2874150/51177303-24faaa80-18b7-11e9-8e91-c9ef9a9dbb01.png)

Not this one, which I'm ambivalent about:

![image](https://user-images.githubusercontent.com/2874150/51177316-317f0300-18b7-11e9-898e-8cdcefc6df20.png)

**Comment by fasterthanlime** [comment]
Right! But changing the upload name every time is wrong from a modelling purpose. Whenever you push v0.16, v0.17 etc., they'll all be builds in a single upload:

  * Dicey Dungeons Windows (upload)
    * Version 0.15.1 (build)
    * Version 0.16.0 (build)
    * Version 0.17.0 (build)

The user can switch to any build they want, here's my install of DD:

![image](https://user-images.githubusercontent.com/7998310/51187153-7e74d080-18db-11e9-9d50-e57c6d570e2c.png)

Currently showing one build:

![image](https://user-images.githubusercontent.com/7998310/51187192-8e8cb000-18db-11e9-904d-67e3738d3468.png)

If you don't like the way the version indicator looks, that's a different issue, which I'm sure we can discuss :)

**Comment by Deozaan** [comment]
If I may chime in, I think a benefit to this suggestion is for people who are not using the Itch app and will download the file(s) manually. It would be nice for the filename of the file that is saved to the Downloads folder to contain the version number as shown in TerryCavanagh's screenshot(s) (e.g., `MyGame v1.15 Windows.zip`). This way a person can tell at a glance or two what version they have already downloaded and what version is the latest available.

**Comment by fasterthanlime** [comment]
> It would be nice for the filename of the file that is saved to the Downloads folder to contain the version number as shown in TerryCavanagh's screenshot(s)

This is a completely separate issue.

The name shown on the downloads page is a "display name", which only appears on the web and doesn't affect downloaded file names. We definitely could make generated .zips include the userversion (or, failing that, the automatically-generated version) string, that actually sounds like a good idea - but the way uploads are displayed on the website has nothing to do with it.

**Comment by fasterthanlime** [comment]
@TerryCavanagh I just want to make sure we're on the same page here, because both this issue and #173 make me think I didn't explain properly how uploads & builds actually work.

## Without butler

When *not* using butler, "uploads" are just files attached to a project. Their name usually includes a version number (because how else are you going to know which version it is?).

Uploading a new version usually involves creating *another* upload, and then removing the old one (or keeping it around, in case folks want to download it again..).

![image](https://user-images.githubusercontent.com/7998310/51983320-aa29b600-2498-11e9-97b4-09f269b7f75f.png)

There's nothing that links uploads "Game v13 for Windows" and "Game v14 for Windows" together - they just happen to be attached to the same game.

In that scenario, 1 upload = 1 file = 1 version, and it *does* make sense to include the version number in the upload name.

## With butler

When you *are* using butler, uploads are "channels", that contain a whole series of versions.

You have a channel for Windows, one for Linux, one for macOS, one for a soundtrack, one for a companion booklet maybe? And all of these can get updated.

When you push a build for Windows/Linux/macOS, it all lands *in the same* uploads. Nothing gets deleted/recreated/renamed.

![image](https://user-images.githubusercontent.com/7998310/51983556-3fc54580-2499-11e9-93d1-411aae3a2c1f.png)

Old builds stick around forever, and users can revert to them from the itch app.

## That issue in particular

Is my "changing the upload name when pushing a build doesn't make sense" stance any clearer now?

Like I said, if you're unhappy with that part: 

![image](https://user-images.githubusercontent.com/7998310/51983645-874bd180-2499-11e9-99bb-061a59a2f058.png)

we can probably change up how it looks. It could look like this for example:

![image](https://user-images.githubusercontent.com/7998310/51983798-ed385900-2499-11e9-98e6-9684263879cd.png)

(although I'm not convinced it's better, because now the versions don't line up anymore)

**Comment by mbasaglia** [comment]
I would like the ability to specify display names too

My use case is this:

Multiple separate download for the same platform/channel

In my specific case I want to upload a zip and a checksum file to allow users to validate the zip.

**Comment by ScionOfDesign** [comment]
I also want this feature. Having to rename builds after every upload is annoying. My use case is that I don't _want_ the user to see the version number, as it is displayed in-game.

**Comment by Mochnant** [comment]
> 2. If you want non-app users to get a file named "Dicey Dungeons Linux (32 bit for compatibility) v0.15.1.zip", when they click 'Download', I can make that happen (don't change upload display names!).

Is this request being tracked somewhere?  I would find it useful.

**Comment by TerryCavanagh** [comment]
Sorry, I should really just close this issue - I've changed how Dicey Dungeons names are displayed on my itch page to better match the intended way itch works, and it's fine! If somebody else wants to request this feature, you should probably open a new issue with an up to date use-case.
