### ISSUE TITLE
wrong magic (invalid input file)

### ISSUE THREAD

**Issue by leafo** [itchio/butler#183]
https://twitter.com/neauoire/status/1098029621457575937

![dzz8gu2vyaedc3e jpg large](https://user-images.githubusercontent.com/15198/53059285-2184b100-346b-11e9-9c32-7697a37b11b5.jpg)

**Comment by fasterthanlime** [comment]
mystery solved: their version of butler was from 2017

![image](https://user-images.githubusercontent.com/7998310/53177917-2d9a7b00-35f1-11e9-9a37-e5e5727a86bc.png)


![image](https://user-images.githubusercontent.com/7998310/53177892-22474f80-35f1-11e9-93e7-1e67b4ba4cdf.png)

**Comment by leafo** [comment]
maybe worth adding a version check when pushing? is there a way for the server to know and send a message back

**Comment by fasterthanlime** [comment]
> maybe worth adding a version check when pushing? is there a way for the server to know and send a message back

well, butler push isn't supposed to break across versions - protobufs allow backward-compatible wire formats, and our signature format hasn't changed ever since the first public release. The only thing that changed is.. we've upgraded the brotli compressor/decompressor. But that's also not supposed to break, content compressed with older versions might be less optimal, but it should always be decompressible with newer versions.

So, I honestly don't know why the push failed with the build of butler from 2017. But, for a year+, butler has been doing update checks on each push, and showing a pretty large message saying to update if they're out-of-date. (We did switch from a GCS bucket to broth/itch.io, but for a few months, versions were deployed to both places).

So, I don't think it's worth it!
