### ISSUE TITLE
Why does `butler fetch` require authentication for public games

### ISSUE THREAD

**Issue by fanmanpro** [itchio/butler#206]
We're looking for a way to download a specific channel and version of a game using butler.

The closest solution seems to be `butler fetch <user/project:channel> <destination>`, however this always prompts to authenticate. Seen in code here: https://github.com/itchio/butler/blob/e020453ca7b0e9fd115ad65511a61c9d15c53ff6/cmd/fetch/fetch.go#L60-L63

I'm curious if there could be a check to first determine if the game is private and only then prompt to authenticate?

Happy to run with the PR if it checks out design wise.

**Comment by fasterthanlime** [comment]
Downloading via the API *always* requires an API key (so, authentication), so that we can monitor usage and, if needed, shut down abuse.

We allow downloading free games via the *website* without an account because we're happy with folks visiting the site, and we're able to recommend them other games, etc.

We provide a platform that graciously offers downloads for free games as long as they're downloaded via the website or our application. We do not offer a free, unlimited, white label CDN :)
