### ISSUE TITLE
Version check failed: Invalid character(s) found in major number "v0"

### ISSUE THREAD

**Issue by Deozaan** [itchio/butler#35]
I tried to push a (first) build and pass in a version number. The push worked but I got an error. The push command I entered (and the accompanying error) were similar to the following:

```
butler push MyFolder username/game:channel --userversion 1.141122.10
Version check failed: Invalid character(s) found in major number "v0"

∙ For channel `channel`: pushing first build

∙ Pushing 48 MB (29 files, 11 dirs, 0 symlinks)
                                    
√ Added 48 MB fresh data
√ 26 MB patch (46.96% savings)
```

Aside: I'm not sure how the first build for a channel has any patch data or any savings.

The error message isn't telling me anything helpful (from my perspective) about what's wrong with my version number. The documentation says:

> However, if you're already generating your own build number, you should pass it to butler with the --userversion option:
>
> `butler push mygame user/mygame:win32-final --userversion 1.1.0`
>
>User-provided version numbers don't have any particular format - the ordering itch.io uses is the one builds are uploaded in.

I interpret this to mean that I can provide any version number I want. This is fairly important to me, since I like to use the date in the version number (141122 == 22 Nov 2014). But something's not working, and I'm not sure why.

Also, is there some place I can see what version number butler/wharf is storing for my uploads to make sure it's being set properly when I push it? Something like itchio/itch.io#398 would be sufficient.

**Comment by Deozaan** [comment]
I'm getting the same error when I try the `butler upgrade` command.

```
PS C:\Users\Deozaan> butler upgrade
∙ Looking for upgrades...
Version check failed: Invalid character(s) found in major number "v0"
PS C:\Users\Deozaan> butler -V
v0.14.0, built on Apr 19 2016 @ 10:49:58
PS C:\Users\Deozaan>
```

**Comment by fasterthanlime** [comment]
This message

> Version check failed: Invalid character(s) found in major number "v0"

Is from butler's self-upgrade mechanism and has nothing to do with your user version. (But worth me looking into! that worked when I last checked.)

> Aside: I'm not sure how the first build for a channel has any patch data or any savings.

It compresses with brotli-q1 while uploading, so you only uploaded 26MB instead of 48MB. It is a patch, from `/dev/null` (the conceptual empty container) to the first build of your game. Having everything be a patch (incl. the first push) is conceptually very clean/simple, feel free to read the specification if you're curious: https://docs.itch.ovh/wharf/master/terminology.html

> Also, is there some place I can see what version number butler/wharf is storing for my uploads to make sure it's being set properly when I push it? Something like itchio/itch.io#398 would be sufficient.

Sure! You just have be an itch.io admin to see it :)

<img width="1326" alt="screen shot 2016-04-23 at 13 21 35" src="https://cloud.githubusercontent.com/assets/7998310/14761086/5d443cee-0956-11e6-9621-271adbebb3a7.png">

Jokes aside, the backend is still very new. When leaf is back from PAX East, I'm sure he'll tackle itchio/itch.io#398 & similar design issues. In the meantime, the main utility of the user version number is the ['anonymous update check' endpoint](https://docs.itch.ovh/butler/master/pushing.html#looking-for-updates).

Since userversion numbers will become more useful in the future (be shown to users/etc.) it's good to set them now so that it works out of the box later. 👍 

Closing this issue since it wasn't one, opening https://github.com/itchio/butler/issues/36 for the message you saw which was unrelated.

**Comment by Deozaan** [comment]
@fasterthanlime thanks for taking the time to explain all this to me. And for fixing things. I appreciate it!

**Comment by fasterthanlime** [comment]
#36 was fixed since btw :)
