### ISSUE TITLE
Avoid renaming .love files to .zip

### ISSUE THREAD

**Issue by technomancy** [itchio/butler#51]
It seems butler is smart enough to realize the `.love` file I uploaded is already a zip file, so it doesn't bother to compress it again. However, it does replace the `.love` extension with `.zip`, which means that GUI users can't just double-click on it to run it.

**Comment by fasterthanlime** [comment]
(Hey @technomancy :) been a while since I used leiningen / did Clojure but I really appreciated it back then! until I [strayed from the beaten path](https://github.com/fasterthanlime/shin) and then switched companies altogether).

Uploading .love (or .jar) files as file hierarchies is actually an unintended feature - fixing the bug (only treating files with the .zip extension as archives) would drop the feature (& generate big patches between compressed data).

I'm still thinking of clean ways to fix that. The generated patch file could have the original file extension in its header, and that could instruct the backend to know which archive type to generate (see #48 - we can't assume the backend will always generate a .zip).

**Comment by technomancy** [comment]
I see; well, good to know. I'll continue uploading .love files by hand till that gets sorted out then; thanks!

**Comment by fasterthanlime** [comment]
@technomancy Actually I guess we'll have to do without the unintended feature for now. Have you tried pushing a folder containing the .love file? Diffing compressed files will probably have poor results, but it is worth a try..
