### ISSUE TITLE
butler upgrade to stable

### ISSUE THREAD

**Issue by HatiEth** [itchio/butler#69]
This could be a documentation error, but with butler upgrade - there seems to be an option to upgrade to stable 

```
$ butler upgrade
√ Bleeding-edge, not upgrading to stable unless told to.
(Use `--head` if you want to upgrade to the latest bleeding-edge version)
```

Specifically talking about **not upgrading to stable unless told to. **. Would be nice to be told how to tell butler to upgrade to stable :)

**Comment by fasterthanlime** [comment]
Ah, you're right. `--head` actually upgrades to bleeding-edge, not to stable. There's actually no way to force butler head to upgrade to stable (which would always be a downgrade anyway)

**Comment by HatiEth** [comment]
But it would be a nice feature to be able to switch channels like say `head` and `stable`. So you do not have to install whole itch.io client on some server you are running to push new builds if tests pass for example :)

**Comment by fasterthanlime** [comment]
@HatiEth actually, since butler is an [ibrew repo](), it's pretty easy to install the latest stable at any point in time:

<img width="1030" alt="screen shot 2016-08-03 at 13 38 18" src="https://cloud.githubusercontent.com/assets/7998310/17364283/99b07746-597f-11e6-9482-dcadce32f3ac.png">

bash command:

```
curl -L "https://dl.itch.ovh/butler/linux-amd64/$(curl https://dl.itch.ovh/butler/linux-amd64/LATEST)/butler" > where/you/want/to/put/butler
```
